version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  app:
    image: node:20.10
    working_dir: /app
    x-develop:
      watch:
        - action: rebuild
          path: .      
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command: sh -c "yarn && yarn dev:local"
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongodb:27017/fine-db
      - PORT=3000
volumes:
  mongodb_data:
